title: My Jekyll Site
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my Jekyll site hosted on GitHub Pages!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://<username>.github.io" # the base hostname & protocol for your site